version: '3'

services:

  metadata-service:
    build: .
    container_name: metadata-service
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
      FLASK_APP: metadata-service
    command: pipenv run flask run --host=0.0.0.0
    labels:
      - "traefik.enable=false"
